name: Automatic testing
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  compile:
    steps:
      name: Compiling Maven
      runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
      - name: Compile
        run: mvn compile
  
  build:
    steps:
      name: Compiling Maven
      runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
      - name: Compile
        run: mvn clean install
