name: Automatic testing
on: [push]

jobs:
  test:
      name: Compiling Maven
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
      - name: Compile
        run: mvn compile
      - name: Test
        run: mvn clean install